### PR TITLE
added categories + nsfw tags (for boards)

### PR DESCRIPTION
**Pull request by saintly2k**
https://github.com/ithrts/ImoutoIB/issues/128

### CODE REVIEW

**Comment by saintly2k** [comment]
check issue for details + screenshots https://github.com/ithrts/ImoutoIB/issues/128

**Comment by ithrts** [comment]
I mostly think it's up to site admins to create their own personalized frontpage for familiarity, but a decent default one is good to have. I like the general idea of this design you chose, it's simple and clear.

The category method in boards.php looks fine to me also. Thumbs up.

We can definitely merge this after some changes, most I will consider small visual bugfixes for consistency.


I'm lazily assuming your website is up to date with the submitted PR by the way so if it isn't do include those changes too:
- I *really* prefer if the boards and posts text dont repeat on every category. It's less clutter if it's only up top. Most sites have very few boards anyways to contain a small community.

Like this: https://i.imgur.com/GBdFUkg.png

- Yotsuba Blue doesn't have the category header background extend all the way, but the others do. It looks much better when it extends all the way. Do the same with yotsuba b as you did the others.
- Tomorrow H2 gets a weird black border-bottom that only applies to the category.
Quickest and laziest way to fix this would be to just add 
``` 
html[data-stylesheet="Tomorrow"] .main .cat h2 {
    border: 0;
}
```
- I'm not sure about Kareha's color. Its kind of unreadable without so I would do something like 
```
html[data-stylesheet="Kareha"] table#boards tr.cat {
    background: #EEF2FF;
    border-left: 1px solid #9f9f9f;
    border-top: 1px solid #9f9f9f;
    border-bottom: 1px solid #fff;
    border-right: 1px solid #fff;
}

html[data-stylesheet="Kareha"] table#boards tr.cat h2 {
    background: #EEF2FF;
}
``` 

- I want the nsfw tag itself to be its own element and not use the css ::after method. This way it's easier to add more tags if desired, using ::after forces the nsfw tag to always be last which could be a negative. Just add a small or span element after the description.
- Remove the black background on the nsfw tag? it hurts my eyes lol

Oh and completely off-topic, but it's "Korean" with a K.


Change this to a commit to your PR and I will test it and merge.

**Comment by saintly2k** [comment]
I really did mistype Korean xd.

I will do all those changes haha

**Comment by saintly2k** [comment]
Okayyy....

- The fix for Yotsuba Blue (with the background) was already in the CSS, just commented since my server had some cashing issues since a few days ago, I just uncommented it and tada
- The boards, description and posts have been added as ``<sub>`` before the table to prevent displaying them all over and over again
- Tomorrow should also be fixed with the weird shadow
- I leave the color choosing for Kareha to you, so I consider it done
- NSFW tag added as small span, ::after removed, same goes with the black background

Seems like I was already that tired a few days ago that I really made a typo in "Korean", thanks for pointing it out hehe.
I also added the Categories to the boardlist,php, screenshots will follow soon

**Comment by saintly2k** [comment]
i have created a new request since i dont know how to fix conflics with my repo, so i deleted it and created a new one again with all the fixes. hopeyou dont mind

**Pull request closed without merging**
